# ruff: noqa: E501
"""Generate release-candidate documents whose claims are copied verbatim from the frozen ledger.

Outputs: the README frozen-results block, a tool/model card, a Hugging Face card draft, and
release notes. Nothing here publishes anything; arXiv, Hugging Face, and release tagging remain
founder actions.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "registry" / "p08_sg000023_paper_evidence"
README_PATH = ROOT / "README.md"
RELEASE_DIR = ROOT / "docs" / "release"
FROZEN_CLAIM_SET_SHA256 = "ef2e347d9ef4298deb68a422c063aa92e9968ae5d00fb0c511576448eb7a2b9b"

BEGIN = "<!-- DAL:FROZEN-RESULTS:BEGIN (generated by tools/build_sg000024_release_docs.py; do not edit) -->"
END = "<!-- DAL:FROZEN-RESULTS:END -->"

DISCLAIMER = (
    "**Research use only.** DAL is not a medical device, has not been clinically validated, and must "
    "not be used for diagnosis, treatment, triage, or any patient-care decision. Nothing here supports "
    "a claim of clinical safety, deployment fitness, or regulatory readiness."
)


def _load(name: str) -> Any:
    return json.loads((PACKAGE / name).read_text(encoding="utf-8"))


def _claims() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    freeze = _load("claim_freeze_manifest.json")
    if freeze["claim_freeze"]["claim_set_sha256"] != FROZEN_CLAIM_SET_SHA256:
        raise ValueError("claim set differs from the SG-000024 frozen binding")
    ledger = _load("claim_ledger.json")
    affirmative = [c for c in ledger["claims"] if c["public_use"] == "affirmative-claim"]
    limitations = [c for c in ledger["claims"] if c["public_use"] == "limitation-statement"]
    return affirmative, limitations


def _claim_lines(claims: list[dict[str, Any]]) -> list[str]:
    return [f"- {claim['text']} (`{claim['claim_id']}`)" for claim in claims]


def _results_block() -> str:
    affirmative, limitations = _claims()
    lines = [
        BEGIN,
        "",
        "Frozen P08 results. Each statement is copied verbatim from the frozen claim ledger "
        f"(claim-set SHA-256 `{FROZEN_CLAIM_SET_SHA256}`).",
        "",
        "**Findings**",
        "",
        *_claim_lines(affirmative),
        "",
        "**Limitations**",
        "",
        *_claim_lines(limitations),
        "",
        END,
    ]
    return "\n".join(lines)


def _model_card() -> str:
    affirmative, limitations = _claims()
    provenance = _load("provenance_index.json")
    freeze = _load("claim_freeze_manifest.json")["final_result_freeze"]
    lines = [
        "<!-- Generated by tools/build_sg000024_release_docs.py; do not edit. -->",
        "# DAL Tool and Model Card (release candidate)",
        "",
        DISCLAIMER,
        "",
        "## What DAL is",
        "",
        "DAL (Decision Assurance Layer) is a research system for clinical typed decisions. Its paper system keeps the action "
        "distribution of a matched BioClinical ModernBERT clinical encoder exactly (it clones and freezes the selected control "
        "head) and adds a calibrated information-sufficiency score that decides whether to commit. Abstaining is a decision "
        "not to commit, never an action.",
        "",
        "## Intended use",
        "",
        "- Reproducing and auditing the frozen P08 evaluation.",
        "- Research on selective prediction, information sufficiency, and evidence-bound reporting.",
        "",
        "Out of scope: any clinical, operational, or patient-facing use.",
        "",
        "## Evaluation",
        "",
        f"Single frozen final evaluation (GitHub Actions run `{freeze['source_final_evaluation_run']}`, artifact "
        f"`{freeze['source_artifact_id']}`). Benchmarks: PubMedQA PQA-L final rows, a constructed native-abstention "
        "variant (each item with evidence present and withheld), and FHIR-AgentBench.",
        "",
        "### Findings",
        "",
        *_claim_lines(affirmative),
        "",
        "### Limitations",
        "",
        *_claim_lines(limitations),
        "",
        "## Weights",
        "",
        "Model weights are **not released**. Redistribution of weights derived from BioClinical ModernBERT awaits a founder "
        "license and redistribution decision.",
        "",
        "## Licensing",
        "",
        "- Code: Apache-2.0 (repository `LICENSE`). It does not override upstream data or model terms.",
        "- PubMedQA: MIT license of its source repository.",
        "- FHIR-AgentBench: CC-BY-4.0 repository; EHR content from EHRSQL (CC-BY-4.0) and the MIMIC-IV demo (ODbL-1.0).",
        "",
        "## Reproducibility",
        "",
        "```bash",
        "python tools/build_sg000023_paper_evidence.py --check",
        "python tools/build_sg000024_manuscript_inputs.py --check",
        "python tools/build_sg000024_release_docs.py --check",
        "```",
        "",
        f"Paper evidence package built against canonical main `{provenance['canonical_main_dependency']}`; "
        f"frozen claim set `{FROZEN_CLAIM_SET_SHA256}`.",
        "",
    ]
    return "\n".join(lines)


def _huggingface_card() -> str:
    affirmative, limitations = _claims()
    lines = [
        "<!-- Generated by tools/build_sg000024_release_docs.py; do not edit. -->",
        "<!-- DRAFT: not published. Publishing needs the founder's Hugging Face account and a license decision. -->",
        "---",
        "license: other",
        "license_name: to-be-confirmed-by-founder",
        "tags:",
        "- clinical-nlp",
        "- selective-prediction",
        "- evaluation",
        "- research-only",
        "---",
        "",
        "# DAL frozen P08 evaluation evidence (draft card)",
        "",
        DISCLAIMER,
        "",
        "This draft describes the frozen DAL evaluation evidence package (`registry/p08_sg000023_paper_evidence/`). "
        "It contains no model weights and no clinical text.",
        "",
        "## Findings",
        "",
        *_claim_lines(affirmative),
        "",
        "## Limitations",
        "",
        *_claim_lines(limitations),
        "",
        "## Citation",
        "",
        "See `CITATION.cff` in the DAL repository.",
        "",
    ]
    return "\n".join(lines)


def _release_notes() -> str:
    affirmative, limitations = _claims()
    lines = [
        "<!-- Generated by tools/build_sg000024_release_docs.py; do not edit. -->",
        "# DAL release notes (draft; no tag has been created)",
        "",
        DISCLAIMER,
        "",
        "## Contents",
        "",
        "- Frozen P08 final-evaluation evidence (`registry/p08_sg000022_final_evaluation/`).",
        "- Paper evidence package, related-work record, and claim freeze (`registry/p08_sg000023_*`).",
        "- Manuscript source (`paper/`), generated from the frozen package.",
        "",
        "## Frozen findings",
        "",
        *_claim_lines(affirmative),
        "",
        "## Known limitations",
        "",
        *_claim_lines(limitations),
        "",
        "## Not included",
        "",
        "- Model weights (pending a founder license decision).",
        "- Fine-tuning notebooks (deferred; they require execution evidence).",
        "- arXiv submission and Hugging Face publication (founder-account actions).",
        "",
    ]
    return "\n".join(lines)


def _readme(current: str) -> str:
    if current.count(BEGIN) != 1 or current.count(END) != 1:
        raise ValueError("README must contain exactly one frozen-results block")
    head, rest = current.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + _results_block() + tail


def build_outputs() -> dict[Path, str]:
    return {
        README_PATH: _readme(README_PATH.read_text(encoding="utf-8")),
        RELEASE_DIR / "MODEL_CARD.md": _model_card(),
        RELEASE_DIR / "HUGGINGFACE_CARD_DRAFT.md": _huggingface_card(),
        RELEASE_DIR / "RELEASE_NOTES_DRAFT.md": _release_notes(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build SG-000024 release-candidate documents")
    parser.add_argument(
        "--check", action="store_true", help="fail unless committed documents match a rebuild"
    )
    args = parser.parse_args()
    outputs = build_outputs()
    if args.check:
        stale = [
            path.relative_to(ROOT).as_posix()
            for path, text in outputs.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != text
        ]
        for name in stale:
            print(f"release document differs from deterministic rebuild: {name}")
        if stale:
            return 1
        print(f"SG-000024 release documents check passed: {len(outputs)} files")
        return 0
    RELEASE_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="\n")
    print(f"SG-000024 release documents built: {len(outputs)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
